[colors.primary]
foreground = "#ffffff"
background = "#240037"

[colors.normal]
black = "#262335"
red = "#ff0040"
green = "#21d375"
yellow = "#f3e70f"
blue = "#0080ff"
magenta = "#ff00ff"
cyan = "#03edf9"
white = "#ffffff"

[colors.bright]
black = "#614d85"
red = "#fe5442"
green = "#21d375"
yellow = "#ffff66"
blue = "#0080ff"
magenta = "#ff7edb"
cyan = "#03edf9"
white = "#ffffff"
