[colors.primary]
background = "#240037"
foreground = "#ffffff"
dim_foreground = "#8f00ff"
bright_foreground = "#ffff66"

[colors.cursor]
text = "#240037"
cursor = "#df00ff"

[colors.vi_mode_cursor]
text = "#240037"
cursor = "#8f00ff"

[colors.search.matches]
foreground = "#240037"
background = "#8f00ff"

[colors.search.focused_match]
foreground = "#240037"
background = "#ffff66"

[colors.footer_bar]
foreground = "#240037"
background = "#8f00ff"

[colors.hints.start]
foreground = "#240037"
background = "#df00ff"

[colors.hints.end]
foreground = "#240037"
background = "#8f00ff"

[colors.selection]
text = "#240037"
background = "#8f00ff"

[colors.normal]
black = "#1a0033"
red = "#ff0080"
green = "#00ff41"
yellow = "#ffff66"
blue = "#0080ff"
magenta = "#8f00ff"
cyan = "#00ffff"
white = "#ffffff"

[colors.bright]
black = "#2a0040"
red = "#ff0080"
green = "#00ff41"
yellow = "#ffff66"
blue = "#0080ff"
magenta = "#8f00ff"
cyan = "#00ffff"
white = "#e0e0ff"

[colors.dim]
black = "#1a0033"
red = "#ff0080"
green = "#00ff41"
yellow = "#ffff66"
blue = "#0080ff"
magenta = "#8f00ff"
cyan = "#00ffff"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#ff4080"

[[colors.indexed_colors]]
index = 17
color = "#8000ff"

